import { PageResponse } from "@/shared/type/model";
import { MyReviewList } from "./model";

export const mockMyReviewPage: PageResponse<MyReviewList> = {
  content: [
    {
      reviewId: 1,
      productId: 101,
      productName: "오버핏 후드티",
      createdAt: "2026-04-01T12:30:00Z",
      rating: 5,
      content: "핏도 좋고 재질도 너무 좋아요. 재구매 의사 있습니다 👍 ",
      imageUrls: ["/images/review1.jpg", "/images/review1.jpg"],
      reply: "소중한 후기 감사합니다 😊",
      replyUpdatedAt: "2026-04-02T10:00:00Z",
      pointStatus: "적립 완료",
      expectedPoint: 500,
    },
    {
      reviewId: 2,
      productId: 102,
      productName: "데일리 슬랙스",
      createdAt: "2026-04-03T09:10:00Z",
      rating: 4,
      content: "사이즈가 조금 크게 나온 것 같아요. 그래도 만족합니다.",
      imageUrls: [],
      reply: null,
      replyUpdatedAt: null,
      pointStatus: "적립금 대기",
      expectedPoint: 300,
    },
    {
      reviewId: 3,
      productId: 103,
      productName: "베이직 반팔티",
      createdAt: "2026-04-05T14:45:00Z",
      rating: 3,
      content: "무난한 제품입니다. 가격 대비 괜찮아요.",
      imageUrls: ["/images/review1.jpg"],
      reply: "더 나은 상품으로 보답하겠습니다.",
      replyUpdatedAt: "2026-04-06T08:20:00Z",
      pointStatus: "적립 완료",
      expectedPoint: 200,
    },
    {
      reviewId: 4,
      productId: 103,
      productName: "베이직 반팔티",
      createdAt: "2026-04-05T14:45:00Z",
      rating: 3,
      content: "무난한 제품입니다. 가격 대비 괜찮아요.",
      imageUrls: ["/images/review1.jpg"],
      reply: "더 나은 상품으로 보답하겠습니다.",
      replyUpdatedAt: "2026-04-06T08:20:00Z",
      pointStatus: "적립금 대기",
      expectedPoint: 200,
    },
    {
      reviewId: 5,
      productId: 103,
      productName: "베이직 반팔티",
      createdAt: "2026-04-05T14:45:00Z",
      rating: 3,
      content: "무난한 제품입니다. 가격 대비 괜찮아요.",
      imageUrls: ["/images/review1.jpg"],
      reply: "더 나은 상품으로 보답하겠습니다.",
      replyUpdatedAt: "2026-04-06T08:20:00Z",
      pointStatus: "적립 완료",
      expectedPoint: 200,
    },

    {
      reviewId: 6,
      productId: 103,
      productName: "베이직 반팔티",
      createdAt: "2026-04-05T14:45:00Z",
      rating: 3,
      content: "무난한 제품입니다. 가격 대비 괜찮아요.",
      imageUrls: ["/images/review1.jpg"],
      reply: "더 나은 상품으로 보답하겠습니다.",
      replyUpdatedAt: "2026-04-06T08:20:00Z",
      pointStatus: "적립금 대기",
      expectedPoint: 200,
    },
  ],

  pageNumber: 0, // API 기준 (0부터)
  pageSize: 10,
  totalElements: 25, // 전체 데이터 개수
  totalPages: 3,
  last: false,
};
